// Per-agent conversation history, stored in ~/.agentic-os/agents/<id>/chat.jsonl.
//
// Two agents wearing the same skin must not share a transcript — that is half of
// what makes "Claude – work" and "Claude – personal" different things — so the
// key is the instance id, never the skin or the Builder.
//
// The CLIs take one prompt string per turn (`execArgs(prompt)`); none of them
// accept a message array. So continuity means packing prior turns into the
// prompt text. That is a real limitation, not a design choice, and packPrompt
// keeps it visible: it trims from the oldest turn and says what it dropped.

import { appendFile, mkdir, readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { AGENTIC_HOME } from "./registry";

export const AGENT_CHATS = path.join(AGENTIC_HOME, "agents");

export interface Turn {
  role: "user" | "assistant";
  text: string;
  ts: string;
  /** Which worker answered this turn (mixed-worker sessions). */
  builder?: string;
  /** Which model produced this turn, when the lane reported one. */
  model?: string;
}

/** Characters of prior conversation to carry. Beyond this the oldest turns go. */
const HISTORY_BUDGET = 12_000;

function chatFile(agentId: string): string {
  // The id is registry-generated by slugify(), but this builds a filesystem path
  // from it, so anything that could climb out of the directory is refused rather
  // than sanitized into something that silently reads a different agent's file.
  if (!/^[a-z0-9][a-z0-9-]*$/.test(agentId)) throw new Error(`"${agentId}" is not a valid agent id.`);
  return path.join(AGENT_CHATS, agentId, "chat.jsonl");
}

export async function readHistory(agentId: string, limit = 40): Promise<Turn[]> {
  const file = chatFile(agentId);
  if (!existsSync(file)) return [];
  let text: string;
  try { text = await readFile(file, "utf8"); }
  catch { return []; }
  const turns: Turn[] = [];
  for (const line of text.split("\n")) {
    if (!line.trim()) continue;
    // One unparseable line is a torn append, not a reason to lose the whole
    // conversation, so it is skipped and the rest is kept.
    try {
      const t = JSON.parse(line) as Turn;
      if ((t.role === "user" || t.role === "assistant") && typeof t.text === "string") turns.push(t);
    } catch { /* skip the damaged line */ }
  }
  return turns.slice(-limit);
}

export async function appendTurn(agentId: string, turn: Turn): Promise<void> {
  const file = chatFile(agentId);
  await mkdir(path.dirname(file), { recursive: true });
  await appendFile(file, JSON.stringify(turn) + "\n", "utf8");
}

/** Forget the conversation but keep the agent and its scratch directory. */
export async function clearHistory(agentId: string): Promise<void> {
  await rm(chatFile(agentId), { force: true });
}

/**
 * Remove everything an agent left on disk: transcript and scratch directory.
 * This is what a purge means — deleting only the transcript would leave empty
 * folders accumulating for every agent the user ever tried.
 */
export async function purgeAgentData(agentId: string): Promise<void> {
  // chatFile validates the id; call it first so a bad id cannot reach rm.
  const dir = path.dirname(chatFile(agentId));
  await rm(dir, { recursive: true, force: true });
}

export interface PackedPrompt {
  text: string;
  /** Turns left out to stay inside the budget, so the UI can say so. */
  dropped: number;
}

/**
 * Fold prior turns into a single prompt string.
 *
 * Oldest-first trimming: the recent turns are the ones the next answer depends
 * on. When anything is dropped the prompt says so, because an agent that
 * silently forgets the start of a conversation looks like it is ignoring you.
 */
export function packPrompt(history: Turn[], prompt: string, budget = HISTORY_BUDGET): PackedPrompt {
  if (!history.length) return { text: prompt, dropped: 0 };

  const lines = history.map((t) => `${t.role === "user" ? "User" : "Assistant"}: ${t.text}`);
  const kept: string[] = [];
  let size = 0;
  for (let i = lines.length - 1; i >= 0; i--) {
    if (size + lines[i].length > budget) break;
    size += lines[i].length + 1;
    kept.unshift(lines[i]);
  }
  const dropped = lines.length - kept.length;
  if (!kept.length) return { text: prompt, dropped };

  const preface = dropped
    ? `[Earlier in this conversation — ${dropped} older turn${dropped === 1 ? "" : "s"} omitted for length.]\n`
    : "[Earlier in this conversation.]\n";
  return { text: `${preface}${kept.join("\n")}\n\nUser: ${prompt}`, dropped };
}
