/** Controller-invoked, loopback-only S10 drill runner. It never prints ownership or lease tokens. */
import { randomBytes } from "node:crypto";
import { existsSync, lstatSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { spawn, type ChildProcess } from "node:child_process";
import { tmpdir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";

const argument = (name: string) => { const index = process.argv.indexOf(name); return index >= 0 ? process.argv[index + 1] : undefined; };
const outputArg = argument("--output"); const reportDirArg = argument("--report-dir");
if (!outputArg || !reportDirArg || !isAbsolute(outputArg) || !isAbsolute(reportDirArg)) throw new Error("--output and --report-dir must be explicit absolute paths.");
const output = resolve(outputArg); const reportDir = resolve(reportDirArg); const outputRelative = relative(reportDir, output);
if (outputRelative === "" || outputRelative.startsWith("..") || isAbsolute(outputRelative) || dirname(output) !== reportDir || basename(output) !== "s10-live-runtime-receipt.json") throw new Error("output must be the explicit s10 receipt directly inside --report-dir.");
if (!existsSync(reportDir) || lstatSync(reportDir).isSymbolicLink()) throw new Error("report directory must be an existing non-link directory.");
if (resolve(realpathSync(reportDir)) !== reportDir) throw new Error("report directory must not resolve outside its supplied workspace path.");
if (existsSync(output) && lstatSync(output).isSymbolicLink()) throw new Error("receipt output must not be a symbolic link.");
const token = randomBytes(32).toString("base64url"); const root = join(tmpdir(), `s10-live-runtime-${randomBytes(12).toString("hex")}`); const children = new Set<ChildProcess>();
const pause = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
function args(reuse = false, cleanup = false, port = "0") { return ["node_modules/tsx/dist/cli.mjs", "tools/s10-live-runtime/daemon.ts", "--runtime-root", root, "--port", port, ...(reuse ? ["--reuse-owned-root"] : []), ...(cleanup ? ["--cleanup"] : [])]; }
function start(port = "0", reuse = false) { const child = spawn(process.execPath, args(reuse, false, port), { cwd: process.cwd(), env: { ...process.env, S10_RUNTIME_OWNERSHIP_TOKEN: token }, stdio: ["ignore", "pipe", "pipe"] }); children.add(child); let out = ""; let err = ""; child.stdout.on("data", (chunk) => { out += chunk; }); child.stderr.on("data", (chunk) => { err += chunk; }); return { child, ready: new Promise<number>((resolveReady, reject) => { const timer = setTimeout(() => reject(new Error("daemon startup timeout")), 5_000); const tick = () => { const match = out.match(/"port":(\d+)/); if (match) { clearTimeout(timer); return resolveReady(Number(match[1])); } if (child.exitCode !== null) { clearTimeout(timer); return reject(new Error(`daemon exited before ready: ${err || "no diagnostic"}`)); } setTimeout(tick, 10); }; tick(); }) }; }
async function stop(child: ChildProcess) { if (child.exitCode !== null || child.signalCode !== null) return; const exited = new Promise<void>((resolveExited) => child.once("exit", () => resolveExited())); child.kill("SIGTERM"); await Promise.race([exited, pause(2_500)]); if (child.exitCode === null && child.signalCode === null) { child.kill("SIGKILL"); await exited; } }
async function cleanup() { await Promise.all([...children].map(stop)); await new Promise<void>((resolveCleanup, reject) => { const child = spawn(process.execPath, args(true, true), { cwd: process.cwd(), env: { ...process.env, S10_RUNTIME_OWNERSHIP_TOKEN: token }, stdio: "ignore" }); child.once("exit", (code) => code === 0 ? resolveCleanup() : reject(new Error("owned cleanup failed"))); }); if (existsSync(root)) throw new Error("owned runtime root remains after cleanup"); }
async function main() { let completed = false; const beganAt = Date.now(); try { const first = start(); const port = await first.ready; const request = async (path: string, payload?: unknown) => { const began = performance.now(); const result = await fetch(`http://127.0.0.1:${port}${path}`, payload ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) } : undefined); return { status: result.status, body: await result.json() as Record<string, unknown>, ms: performance.now() - began }; };
    if ((await request("/health")).status !== 200) throw new Error("health drill failed");
    if ((await request("/action/approval", { candidate: "candidate-a", decision: "reject" })).body.noOp !== true) throw new Error("rejection/no-op drill failed");
    if ((await request("/action/canary", { candidate: "candidate-a", observations: [{ errorRate: 0 }] })).status !== 409) throw new Error("approval gate drill failed");
    await request("/action/approval", { candidate: "candidate-a", decision: "approve" }); const canary = await request("/action/canary", { candidate: "candidate-a", observations: [{ errorRate: 0 }] }); if (canary.body.outcome !== "canary-passed-advisory") throw new Error("canary drill failed");
    if ((await request("/action/outbox", { id: "event-a" })).body.delivered !== 1 || (await request("/action/outbox", { id: "event-a" })).body.suppressedDuplicate !== true) throw new Error("outbox drill failed");
    const leaseA = await request("/action/lease", { owner: "owner-a", ttlMs: 100 }); if (leaseA.status !== 200) throw new Error("lease acquisition failed"); const tokenA = Number(leaseA.body.fencingToken); if ((await request("/action/mutate", { owner: "owner-a", fencingToken: tokenA, mutation: "first" })).status !== 200) throw new Error("valid lease mutation failed"); await pause(120); const leaseB = await request("/action/lease", { owner: "owner-b", ttlMs: 500 }); const tokenB = Number(leaseB.body.fencingToken); if (leaseB.status !== 200 || tokenB <= tokenA) throw new Error("lease replacement failed"); const beforeStale = await request("/status"); if ((await request("/action/mutate", { owner: "owner-a", fencingToken: tokenA, mutation: "stale" })).status !== 409) throw new Error("stale lease did not fail closed"); const afterStale = await request("/status"); if (afterStale.body.durableMutations !== beforeStale.body.durableMutations) throw new Error("stale lease mutated durable state");
    const snapshot = await request("/action/snapshot", { name: "before-rollback" }); await pause(5); const mutation = await request("/action/rollback", {}); const restore = await request("/action/restore", { name: "before-rollback" }); if (restore.status !== 200) throw new Error("restore drill failed"); const rpoMs = Number(mutation.body.persistedAt) - Number(snapshot.body.persistedAt); await request("/action/backend", { available: false }); if ((await request("/action/rollback", {})).status !== 503) throw new Error("backend unavailable did not fail closed"); await request("/action/backend", { available: true });
    const beforeRestart = await request("/status"); const restartAt = Date.now(); await stop(first.child); const second = start(String(port), true); await second.ready; const afterRestart = await request("/status"); const rtoMs = Date.now() - restartAt; if (afterRestart.body.delivered !== beforeRestart.body.delivered) throw new Error("restart lost durable outbox state"); await cleanup();
    const receipt = { marker: "JOB_DONE", runtime: "isolated-loopback-only", drills: ["restart-recovery", "snapshot-restore", "duplicate-outbox", "expired-and-replaced-lease-fencing", "backend-unavailable", "approval-rejection-no-op", "monitored-canary", "rollback"], sloMs: Math.round(canary.ms), rpoMs, rtoMs, elapsedMs: Date.now() - beganAt, cleanupVerified: true, legacyWriter: "disabled", phase21: "blocked", secrets: "none" }; const temporaryOutput = `${output}.tmp`; writeFileSync(temporaryOutput, `${JSON.stringify(receipt, null, 2)}\n`, { encoding: "utf8", flag: "w" }); renameSync(temporaryOutput, output); completed = true;
  } finally { if (!completed && existsSync(root)) { try { await cleanup(); } catch { /* preserve the original failure without exposing tokens */ } } }
}
main().then(() => process.stdout.write("S10 live runtime drill completed; receipt written.\n")).catch((error) => { process.stderr.write(`${error instanceof Error ? error.message : "drill failed"}\n`); process.exitCode = 1; });
