<#
.SYNOPSIS
    Disk-only staging engine for agent Headroom configuration.
.DESCRIPTION
    Writes .env files and parameters to the profile's disk configuration folder
    WITHOUT touching current process RAM environment variables, preventing in-flight
    disconnection.
#>

$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptRoot
if (-not (Test-Path -LiteralPath (Join-Path $RepoRoot "core\registry.ps1"))) {
    $RepoRoot = (Get-Location).Path
}

. (Join-Path $RepoRoot "core\registry.ps1")
. (Join-Path $RepoRoot "core\port-allocator.ps1")

function Stage-AgentProfileHeadroom {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$ProfileName,

        [Parameter(Mandatory = $true)]
        [string]$ConfigDir,

        [string]$Upstream = "http://127.0.0.1:9284",

        [string]$AgentType = "claude",

        [int]$Port = 0
    )

    if (-not (Test-Path -LiteralPath $ConfigDir)) {
        New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
    }

    # 1. Allocate safe port if not specified
    if ($Port -le 0) {
        $reg = Get-TokenStackRegistry
        $reserved = @()
        foreach ($p in $reg.profiles.PSObject.Properties) {
            if ($p.Name -ne $ProfileName -and $p.Value.headroom_port) {
                $reserved += [int]$p.Value.headroom_port
            }
        }
        $Port = Find-FreeHeadroomPort -IncludeRunningProcesses -ReservedPorts $reserved
    }

    # 2. Allocate isolated SQLite DB path
    $dbPath = Join-Path $ConfigDir "headroom-data\headroom.db"
    Ensure-ProfileDbDirectory $dbPath

    # 3. Update centralized registry
    $profileConfig = @{
        type          = $AgentType
        config_dir    = $ConfigDir
        headroom_port = $Port
        upstream      = $Upstream
        db_path       = $dbPath
    }
    Set-TokenStackProfile -Name $ProfileName -Config $profileConfig

    # 4. Write disk-only .env staging file (DO NOT mutate $env: in current process!)
    $envFile = Join-Path $ConfigDir ".env"
    $envContent = @"
# Generated by Token-Stack Safe Staging Engine
ANTHROPIC_BASE_URL=http://127.0.0.1:$Port
OPENAI_BASE_URL=http://127.0.0.1:$Port/v1
HEADROOM_PORT=$Port
HEADROOM_UPSTREAM=$Upstream
HEADROOM_DB_PATH=$dbPath
"@
    [System.IO.File]::WriteAllText($envFile, $envContent, [System.Text.UTF8Encoding]::new($false))

    # 5. Refresh Markdown documentation note
    $docPath = Join-Path $RepoRoot "docs\headroom-ports.md"
    Export-HeadroomPortNote -OutputPath $docPath | Out-Null

    # 6. Inject SessionStart Hook into agent settings.json
    $injectorScript = Join-Path $RepoRoot "core\hook-injector.ps1"
    $hookResult = $null
    if (Test-Path -LiteralPath $injectorScript) {
        . $injectorScript
        $hookResult = Inject-SessionStartHook -ConfigDir $ConfigDir -AgentType $AgentType
    }

    return [PSCustomObject]@{
        ProfileName = $ProfileName
        ConfigDir   = $ConfigDir
        Port        = $Port
        Upstream    = $Upstream
        DbPath      = $dbPath
        EnvFile     = $envFile
        HookFile    = if ($hookResult) { $hookResult.TargetFile } else { $null }
        Status      = "Staged (Restart Required)"
    }
}

if ($ExecutionContext.SessionState.Module) {
    Export-ModuleMember -Function Stage-AgentProfileHeadroom
}
